2024-05-07 14:55:52,565 - INFO - 
======================================================================
STARTING UP.............................
  Date and Time:    2024-05-07 at 02:55 PM
  Operating System: nt Windows 10
  Python Version:   3.11.5
  Path to Interpreter:  C:\Users\cjack\anaconda3\python.exe
======================================================================

2024-05-07 14:55:52,565 - INFO - Called recreate_database().
2024-05-07 14:55:52,565 - INFO - Called drop_table().
2024-05-07 14:55:52,579 - INFO - Table 'pets' dropped successfully.
2024-05-07 14:55:52,579 - INFO - Called create_table().
2024-05-07 14:55:52,584 - INFO - Table 'pets' created successfully.
2024-05-07 14:55:52,757 - INFO - Called process_two().
2024-05-07 14:55:52,757 - INFO -   Called insert_pet() with process=P2, name=Cooper, breed=Rabbit.
2024-05-07 14:55:52,765 - INFO - Called process_one().
2024-05-07 14:55:52,766 - INFO -   Called insert_pet() with process=P1, name=Ace, breed=Dog.
2024-05-07 14:55:52,772 - INFO - Called process_three().
2024-05-07 14:55:52,773 - INFO -   Called insert_pet() with process=P3, name=Emma, breed=Rabbit.
2024-05-07 14:55:55,770 - INFO -   Called insert_pet() with process=P2, name=Dingo, breed=Dog.
2024-05-07 14:55:58,370 - ERROR - ERROR while P1 inserting pet Ace: database is locked
2024-05-07 14:55:58,371 - INFO -   Called insert_pet() with process=P1, name=Buddy, breed=Dog.
2024-05-07 14:55:58,401 - ERROR - ERROR while P3 inserting pet Emma: database is locked
2024-05-07 14:55:58,402 - INFO -   Called insert_pet() with process=P3, name=Felix, breed=Cat.